### ISSUE TITLE
Virtual deck

### ISSUE THREAD

**Issue by Madis0** [NucleoidMC/Last-Card#3]
There should also be a virtual deck in the game.

Perhaps 2x3 layers of snow with an active card/card back overlay (done with an armor stand).

**Comment by haykam821** [comment]
A card display now shows the card deck, including the draw and discard piles:

<img width="1440" alt="Card pile display" src="https://user-images.githubusercontent.com/24855774/184265476-7aafad7c-fcbb-4223-8566-d7527bfaeda6.png">
